# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('comment_count', models.IntegerField(default=0)),
                ('view_num', models.IntegerField(default=0)),
            ],
        ),
    ]
