# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='demo',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
