# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170320_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('publish_time', models.DateTimeField(verbose_name='Date Published')),
                ('intro', models.TextField()),
                ('view', models.IntegerField(default=0)),
                ('tp', models.CharField(max_length=10)),
                ('tags', models.ManyToManyField(to='blog.Tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='demo',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
