# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170320_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Post')),
                ('content', models.TextField()),
            ],
            bases=('blog.post',),
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Post')),
                ('html', models.CharField(max_length=30)),
            ],
            bases=('blog.post',),
        ),
        migrations.RemoveField(
            model_name='post',
            name='tp',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
