# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170320_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='css',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='demo',
            name='js',
            field=models.TextField(null=True),
        ),
    ]
