# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('post_id', models.IntegerField()),
                ('content', models.TextField()),
                ('publish_tim', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
