# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remark', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remark',
            old_name='publish_tim',
            new_name='publish_time',
        ),
    ]
