# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remark', '0002_auto_20170322_1124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Remark',
        ),
    ]
