# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170323_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ismajor',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
